title: Create a Beautiful Documentation Website for your Github Project
description: A step-by-step tutorial for how to create and style a documentation 
website for your Github Project (no coding necessary). 
theme: jekyll-theme-hacker
